export interface ProjectItemType {
  id: string;
  category: string;
  name: string;
  desc: string;
  module: string[];
  images: string | string[];
  mainLink: string;
  links: string[] | undefined;
}
export const ProjectCardItem = [
  {
    id: 9,
    category: 'Website',
    logo: '',
    name: 'RE:VENTURES',
    desc: 'The official website of company called RE:VENTURES. The client requested a feature that upload contents from user inputs and show them on the pages. The headless CMS has implemented using Wordpress.',
    features: [
      'Upload data on Wordpress, fetch data on client side',
      'Send email with form attached file',
      'Smooth transition using Framer-motion',
    ],
    module: [
      { icon: '/next.png', name: 'Next JS' },
      { icon: '/typescript.png', name: 'Typescript' },
      { icon: '/tailwindcss.png', name: 'tailwindcss' },
      { icon: '/graph.png', name: 'GraphQL' },
      { icon: '/apollo.png', name: 'Apollo Client' },
      { icon: '/react-hook-form.png', name: 'react-hook-form' },
      { icon: '/wp.png', name: 'Headless CMS' },
      { icon: '/jest.png', name: 'jest' },
      { icon: '/cypress.png', name: 'cypress' },
    ],
    images: [
      '/reventures_1.png',
      '/reventures_2.png',
      '/reventures_3.png',
      '/reventures_4.png',
    ],
    links: undefined,
    mainLink: 'https://www.reventures.co.kr/',
    color: '#7d7d7d',
  },
  {
    id: 8,
    category: 'Console',
    logo: '/gorae_logo.png',
    name: 'Gorae Market Admin Dashboard',
    desc: 'The web application that control over the seafood E-commerce platform called Gorae Market. The most of back end APIs are developed with Firebase Cloud Functions. The payment gateway and shipment tracking systems are implemented using Express',
    features: [
      'Register admin accounts / Assign custom permissions',
      'Upload assets with file management / Manage product reviews',
      'Upload / Modify products',
      'Create sales coupon',
      'Track shipments',
    ],
    module: [
      { icon: '/react.png', name: 'React' },
      { icon: '/antd.png', name: 'Ant Design' },
      { icon: '/tailwindcss.png', name: 'tailwindcss' },
      { icon: '/node.png', name: 'Node JS' },
      { icon: '/expressjs-icon.png', name: 'Express' },
      { icon: '/firebase.png', name: 'Firebase' },
      { icon: '/typescript.png', name: 'TypeScript' },
      { icon: '/jest.png', name: 'jest' },
      { icon: '/cypress.png', name: 'cypress' },
    ],
    images: [
      '/gorae_1.png',
      '/gorae_2.png',
      '/gorae_3.png',
      '/gorae_4.png',
      '/gorae_5.png',
      '/gorae_6.png',
    ],
    mainLink: '',
    links: undefined,
    color: '#2464d7',
  },
  {
    id: 7,
    category: 'Platform',
    logo: '/papaya-logo.png',
    name: 'Papaya Play Portal',
    desc: 'The web platforms that inform news, events, updates of games, purchase the game cash with cross platform billing APIs (Xsolla, Paypal, etc), manage the game forum based on vanilla forum, connect user to helpdesk',
    features: [
      'Register user accounts / Login with oauth 2.0',
      'Provide English, French, German, Turkish, Portuguese, Malay',
      'Notifications for Upcoming Events',
      'Provide Cashshop to purchase game currency',
      'View transaction log',
    ],
    module: [
      { icon: '/vue.png', name: 'Vue' },
      { icon: '/sass.png', name: 'Sass' },
      { icon: '/jquery.png', name: 'jquery' },
      { icon: '/bootstrap.png', name: 'bootstrap' },
      { icon: '/gsap.png', name: 'GSAP' },
    ],
    images: [
      '/papaya_1.png',
      '/papaya_2.png',
      '/papaya_3.png',
      '/papaya_4.png',
      '/papaya_5.png',
    ],
    mainLink: 'https://www.papayaplay.com',
    links: undefined,
    color: '#518a6b',
  },
  {
    id: 6,
    category: 'Console',
    logo: '/papaya-logo.png',
    name: 'Papaya Play Admin Dashboard',
    desc: 'An application that give you control over the Papaya Play Portal.',
    features: [
      'Register admin accounts',
      'Block suspicious accounts',
      'Assign custom permissions',
      'Publish / Modify notification, events, and news',
      'Upload assets with file management',
      'Build visualization chart based on statistics',
      'Configure the elements of the web contents (eg.Gacha, webshop)',
      'Show sales log table / Refund logs',
    ],
    module: [
      { icon: '/vue.png', name: 'Vue' },
      { icon: '/vuex.png', name: 'Vuex' },
      { icon: '/vuetify.png', name: 'Vuetify' },
      { icon: '/axios.png', name: 'Axios' },
      { icon: '/chartjs.png', name: 'Chart.js' },
      { icon: '/tinymce.png', name: 'TinyMCE' },
      { icon: '/jest.png', name: 'jest' },
    ],
    images: [
      '/papaya-admin_1.png',
      '/papaya-admin_2.png',
      '/papaya-admin_3.png',
      '/papaya-admin_4.png',
      '/papaya-admin_5.png',
      '/papaya-admin_6.png',
      '/papaya-admin_7.png',
    ],
    mainLink: '',
    links: undefined,
    color: '#518a6b',
  },
  {
    id: 5,
    category: 'Website',
    logo: '/vertigo-logo.png',
    name: 'Vertigo Games',
    desc: 'The official website that introduce the company. Implemented Headless WordPress that manage backend contents while front-end developer access the data via APIs',
    features: [
      'Provide two languages (Korean, English)',
      'Introduce game services',
      'Post News and careers',
    ],
    module: [
      { icon: '/react.png', name: 'React' },
      { icon: '/styled-components.png', name: 'styled-component' },
      { icon: '/typescript.png', name: 'TypeScript' },
      { icon: '/intl.png', name: 'react-intl' },
      { icon: '/wp.png', name: 'Headless CMS' },
      { icon: '/jest.png', name: 'jest' },
    ],
    images: [
      '/vertigo_1.png',
      '/vertigo_2.png',
      '/vertigo_3.png',
      '/vertigo_4.png',
      '/vertigo_5.png',
    ],
    mainLink: 'https://vertigogames.com/',
    links: undefined,
    color: '#bf803b',
  },
  {
    id: 4,
    category: 'Platform',
    logo: '/uwo-logo.png',
    name: 'Uncharted Waters Online',
    desc: 'The official website of game called Uncharted Waters Online. I developed the webshop that sells unique items',
    features: [
      'Introduce game services',
      'Check Events, and News',
      'Purchase items on Webshop',
      'Play Gacha on the page',
    ],
    module: [
      { icon: '/vue.png', name: 'Vue' },
      { icon: '/sass.png', name: 'Sass' },
      { icon: '/jquery.png', name: 'jquery' },
      { icon: '/gsap.png', name: 'GSAP' },
    ],
    images: [
      '/uwo_1.png',
      '/uwo_2.png',
      '/uwo_3.png',
      '/uwo_4.png',
      '/uwo_5.png',
    ],
    mainLink: 'https://uwo.papayaplay.com/',
    links: undefined,
    color: '#dce7fa',
  },
  {
    id: 3,
    category: 'Platform',
    logo: '/wr_logo.png',
    name: 'WarRock',
    desc: 'The official website of game called WarRock. Developed Web Gacha system to provide more entertainment.',
    features: [
      'Introduce game services',
      'Check Events, and News',
      'Purchase items on Webshop',
      'Play Gacha on the page',
    ],
    module: [
      { icon: '/vue.png', name: 'Vue' },
      { icon: '/sass.png', name: 'Sass' },
      { icon: '/jquery.png', name: 'jquery' },
      { icon: '/gsap.png', name: 'GSAP' },
    ],
    images: [
      '/warrock_1-min.png',
      '/warrock_2-min.png',
      '/warrock_3-min.png',
      '/warrock_4-min.png',
    ],
    mainLink: 'https://warrock.papayaplay.com/',
    links: undefined,
    color: '#1b1b1b',
  },
  {
    id: 2,
    category: 'Platform',
    logo: '/lt_logo.png',
    name: 'La Tale Online',
    desc: 'The official website of game called LaTale. The game is well known for the BGM, Developed music player into the website',
    features: [
      'Introduce game services',
      'Check Events, and News',
      'Experience contents such as music, and videos',
    ],
    module: [
      { icon: '/vue.png', name: 'Vue' },
      { icon: '/sass.png', name: 'Sass' },
      { icon: '/jquery.png', name: 'jquery' },
      { icon: '/bootstrap.png', name: 'bootstrap' },
      { icon: '/gsap.png', name: 'GSAP' },
    ],
    images: ['/lt_1.png', '/lt_2.png', '/lt_3.png', '/lt_4.png', '/lt_5.png'],
    mainLink: 'https://latale.papayaplay.com/',
    links: undefined,
    color: '#d8c838',
  },

  {
    id: 1,
    category: 'E-Commerce',
    logo: '/hiossen-logo.png',
    name: 'Hiossen Implant Shop',
    desc: 'An E-commerce platform that registered doctor can order the implant equipments. The option and quantity of items can be configure in shopify admin panel. View order status and history in account',
    features: ['Shop Products relates to dental implant'],
    module: [{ icon: '/shopify.png', name: 'Shopify' }],
    images: ['/hiossen_1.png', '/hiossen_2.png'],
    mainLink: 'https://denall.ca/',
    links: undefined,
    color: '#b24d67',
  },
];
